import type { SourceBundle } from './types';

const ACME_SCHEMA =
  '{"type":"struct","fields":[' +
  '{"name":"supplier_id","type":"string","nullable":true,"metadata":{}},' +
  '{"name":"sku","type":"string","nullable":true,"metadata":{}},' +
  '{"name":"product_name","type":"string","nullable":true,"metadata":{}},' +
  '{"name":"qty_on_hand","type":"integer","nullable":true,"metadata":{}},' +
  '{"name":"unit_cost","type":"double","nullable":true,"metadata":{}},' +
  '{"name":"last_updated","type":"string","nullable":true,"metadata":{}}]}';

/**
 * The six demo sources mirroring src/sql/02_seed_metadata.sql. Seeded into
 * Lakebase on first startup so the UI is populated, and re-published into the
 * Delta metadata tables the framework reads.
 */
export const SEED_SOURCES: SourceBundle[] = [
  {
    source: {
      object_id: 'src_pos_transactions',
      storage_account: null,
      container: null,
      file_path: '/Volumes/autoloader_demo/landing/raw/pos/transactions/',
      wildcard_pattern: '*.parquet',
      file_format: 'parquet',
      row_tag: null,
      object_schema: null,
      delimiter: null,
      encoding: null,
      null_value: null,
      description: 'POS transaction feed from stores (Parquet, append-only events)',
    },
    target: {
      object_id: 'tgt_pos_transactions',
      target_catalog: 'autoloader_demo',
      target_schema: 'bronze',
      target_table: 'pos_transactions',
      table_path: null,
      partition_cols: 'load_date',
      merge_keys: null,
      description: 'Bronze POS transactions (partitioned by load_date)',
    },
    operation: {
      operation_id: 'op_pos_transactions',
      enabled: true,
      source_object_id: 'src_pos_transactions',
      target_object_id: 'tgt_pos_transactions',
      load_type: 'append',
      merge_schema: true,
      schema_evolution_mode: 'addNewColumns',
      cast_all_as_string: false,
      multiline: false,
      case_sensitive: false,
      max_files_per_trigger: 1000,
      explode_key: null,
      description: 'Append POS Parquet; evolve schema additively',
    },
  },
  {
    source: {
      object_id: 'src_supplier_acme',
      storage_account: null,
      container: null,
      file_path: '/Volumes/autoloader_demo/landing/raw/suppliers/acme/',
      wildcard_pattern: '*.csv',
      file_format: 'csv',
      row_tag: null,
      object_schema: ACME_SCHEMA,
      delimiter: '|',
      encoding: 'UTF-8',
      null_value: 'NULL',
      description: 'Supplier ACME inventory (headerless pipe-delimited CSV, explicit schema)',
    },
    target: {
      object_id: 'tgt_supplier_acme',
      target_catalog: 'autoloader_demo',
      target_schema: 'bronze',
      target_table: 'supplier_acme_inventory',
      table_path: null,
      partition_cols: null,
      merge_keys: null,
      description: 'Bronze supplier ACME inventory',
    },
    operation: {
      operation_id: 'op_supplier_acme',
      enabled: true,
      source_object_id: 'src_supplier_acme',
      target_object_id: 'tgt_supplier_acme',
      load_type: 'append',
      merge_schema: true,
      schema_evolution_mode: 'none',
      cast_all_as_string: false,
      multiline: false,
      case_sensitive: false,
      max_files_per_trigger: 1000,
      explode_key: null,
      description: 'Append supplier ACME headerless pipe CSV using explicit schema',
    },
  },
  {
    source: {
      object_id: 'src_crm_customers',
      storage_account: null,
      container: null,
      file_path: '/Volumes/autoloader_demo/landing/raw/crm/customers/',
      wildcard_pattern: '*.json',
      file_format: 'json',
      row_tag: null,
      object_schema: null,
      delimiter: null,
      encoding: null,
      null_value: null,
      description: 'CRM customer master extract (JSON, represents current state -> merge)',
    },
    target: {
      object_id: 'tgt_crm_customers',
      target_catalog: 'autoloader_demo',
      target_schema: 'bronze',
      target_table: 'crm_customers',
      table_path: null,
      partition_cols: null,
      merge_keys: 'customer_id',
      description: 'Bronze CRM customers (upsert keyed on customer_id)',
    },
    operation: {
      operation_id: 'op_crm_customers',
      enabled: true,
      source_object_id: 'src_crm_customers',
      target_object_id: 'tgt_crm_customers',
      load_type: 'merge',
      merge_schema: true,
      schema_evolution_mode: 'addNewColumns',
      cast_all_as_string: false,
      multiline: true,
      case_sensitive: false,
      max_files_per_trigger: 1000,
      explode_key: null,
      description: 'Merge CRM customers on customer_id (multiline JSON)',
    },
  },
  {
    source: {
      object_id: 'src_supplier_edi',
      storage_account: null,
      container: null,
      file_path: '/Volumes/autoloader_demo/landing/raw/suppliers/edi/',
      wildcard_pattern: '*.xml',
      file_format: 'xml',
      row_tag: 'Order',
      object_schema: null,
      delimiter: null,
      encoding: null,
      null_value: null,
      description: 'Supplier EDI purchase orders (XML, rowTag=Order)',
    },
    target: {
      object_id: 'tgt_supplier_edi',
      target_catalog: 'autoloader_demo',
      target_schema: 'bronze',
      target_table: 'supplier_edi_orders',
      table_path: null,
      partition_cols: null,
      merge_keys: null,
      description: 'Bronze supplier EDI orders',
    },
    operation: {
      operation_id: 'op_supplier_edi',
      enabled: true,
      source_object_id: 'src_supplier_edi',
      target_object_id: 'tgt_supplier_edi',
      load_type: 'append',
      merge_schema: true,
      schema_evolution_mode: 'addNewColumns',
      cast_all_as_string: false,
      multiline: false,
      case_sensitive: false,
      max_files_per_trigger: 1000,
      explode_key: null,
      description: 'Append supplier EDI XML orders (rowTag=Order)',
    },
  },
  {
    source: {
      object_id: 'src_clickstream',
      storage_account: null,
      container: null,
      file_path: '/Volumes/autoloader_demo/landing/raw/clickstream/events/',
      wildcard_pattern: '*.jsonl',
      file_format: 'jsonl',
      row_tag: null,
      object_schema: null,
      delimiter: null,
      encoding: null,
      null_value: null,
      description: 'Web clickstream export (JSONL, records wrapped in an events[] array)',
    },
    target: {
      object_id: 'tgt_clickstream',
      target_catalog: 'autoloader_demo',
      target_schema: 'bronze',
      target_table: 'clickstream_events',
      table_path: null,
      partition_cols: null,
      merge_keys: null,
      description: 'Bronze clickstream events (one row per exploded event)',
    },
    operation: {
      operation_id: 'op_clickstream',
      enabled: true,
      source_object_id: 'src_clickstream',
      target_object_id: 'tgt_clickstream',
      load_type: 'append',
      merge_schema: true,
      schema_evolution_mode: 'addNewColumns',
      cast_all_as_string: false,
      multiline: false,
      case_sensitive: false,
      max_files_per_trigger: 1000,
      explode_key: 'events',
      description: 'Append clickstream JSONL; explode top-level events[] array',
    },
  },
  {
    source: {
      object_id: 'src_loyalty_history',
      storage_account: null,
      container: null,
      file_path: '/Volumes/autoloader_demo/landing/raw/crm/loyalty_history/',
      wildcard_pattern: '*.csv',
      file_format: 'csv',
      row_tag: null,
      object_schema: null,
      delimiter: ',',
      encoding: 'UTF-8',
      null_value: '',
      description:
        'Five years of loyalty history (CSV). customer_tier drifted numeric->string across years',
    },
    target: {
      object_id: 'tgt_loyalty_history',
      target_catalog: 'autoloader_demo',
      target_schema: 'bronze',
      target_table: 'loyalty_history',
      table_path: null,
      partition_cols: null,
      merge_keys: null,
      description: 'Bronze loyalty history (faithful capture, all columns as STRING)',
    },
    operation: {
      operation_id: 'op_loyalty_history',
      enabled: true,
      source_object_id: 'src_loyalty_history',
      target_object_id: 'tgt_loyalty_history',
      load_type: 'append',
      merge_schema: true,
      schema_evolution_mode: 'rescue',
      cast_all_as_string: true,
      multiline: false,
      case_sensitive: false,
      max_files_per_trigger: 1000,
      explode_key: null,
      description: 'Historical loyalty load; cast_all_as_string survives multi-year type drift',
    },
  },
];
