// Auto-generated by AppKit - DO NOT EDIT
// Generated by 'npx @databricks/appkit generate-types' or Vite plugin during build
import "@databricks/appkit-ui/react";
import type { SQLTypeMarker, SQLStringMarker, SQLNumberMarker, SQLBooleanMarker, SQLBinaryMarker, SQLDateMarker, SQLTimestampMarker } from "@databricks/appkit-ui/js";

declare module "@databricks/appkit-ui/react" {
  interface QueryRegistry {
    audit_latest: {
        name: "audit_latest";
        parameters: Record<string, never>;
        result: Array<{
          /** Operation that ran */
          operation_id: string;
          /** Run completion timestamp */
          run_ts: string;
          /** SUCCESS | FAILED */
          status: string;
          /** Rows written across all micro-batches in this run */
          rows_written: number;
          /** Wall-clock duration in milliseconds */
          duration_ms: number;
        }>;
      };
    bronze_columns: {
        name: "bronze_columns";
        parameters: Record<string, never>;
        result: Array<{
          /** Name of the relation the column is part of. */
          table_name: string;
          /** Name of the column. */
          column_name: string;
          /** The data type as specified in the column definition. */
          full_data_type: string;
          /** YES if column is nullable, NO otherwise. */
          is_nullable: string;
          /** The position (numbered from 1) of the column within the relation. */
          ordinal_position: number;
        }>;
      };
    bronze_tables: {
        name: "bronze_tables";
        parameters: Record<string, never>;
        result: Array<{
          /** Name of the relation. */
          table_name: string;
          /** Type of the table such as 'MANAGED', 'FOREIGN', 'VIEW', etc. */
          table_type: string;
          /** Format of the data source such as PARQUET, or CSV. */
          data_source_format: string;
        }>;
      };
  }
}
