-- =====================================================================================
-- Metadata-Driven Autoloader Framework — DDL
-- -------------------------------------------------------------------------------------
-- Creates the control plane for a source-agnostic ingestion framework built on
-- Databricks Auto Loader (cloudFiles). A single parameterized notebook reads ALL of its
-- behavior (path, file format, schema, write mode, schema evolution, parsing quirks)
-- from these metadata tables at runtime. Onboarding a new source is a metadata INSERT,
-- not a code deployment.
--
-- Inspired by: "Stop Writing Ingestion Pipelines. Build a Framework Instead" (D. Goyal)
--
-- Object model:
--   object   -> registry of SOURCE and TARGET data objects (sparse, type-discriminated)
--   operation-> binds a source object to a target object + the run behavior
--   ingestion_audit_log -> one row per framework run (status, duration, rows, errors)
--
-- This script is idempotent (CREATE ... IF NOT EXISTS). Run it once per environment.
-- Default namespace is `autoloader_demo`; change the catalog name below if needed.
-- =====================================================================================

-- ─────────────────────────────────────────────────────────────────────────────────────
-- 0. Catalog, schemas and volumes
--    metadata : framework control tables
--    bronze   : landed (faithful-capture) target tables
--    landing  : volumes holding raw source files + Auto Loader checkpoints
-- ─────────────────────────────────────────────────────────────────────────────────────
CREATE CATALOG IF NOT EXISTS autoloader_demo
  COMMENT 'Demo catalog for the metadata-driven Auto Loader ingestion framework';

CREATE SCHEMA IF NOT EXISTS autoloader_demo.metadata
  COMMENT 'Framework control plane: object registry, operations, and audit log';

CREATE SCHEMA IF NOT EXISTS autoloader_demo.bronze
  COMMENT 'Bronze layer — faithful capture of source data (no business typing)';

CREATE SCHEMA IF NOT EXISTS autoloader_demo.landing
  COMMENT 'Landing zone — UC volumes for raw source files and Auto Loader checkpoints';

-- Raw source files generated by 00_generate_sample_data live here.
CREATE VOLUME IF NOT EXISTS autoloader_demo.landing.raw
  COMMENT 'Raw inbound source files (POS, supplier, CRM, ERP, clickstream, EDI)';

-- Each operation gets its own checkpoint subfolder under this volume.
CREATE VOLUME IF NOT EXISTS autoloader_demo.landing.checkpoints
  COMMENT 'Auto Loader per-operation checkpoints (file tracking + schema location)';


-- ─────────────────────────────────────────────────────────────────────────────────────
-- 1. object — unified registry of source and target data objects
--    A row is either a SOURCE (where/how to read) or a TARGET (where/how to write).
--    Columns are sparse: source rows leave target_* NULL and vice-versa.
-- ─────────────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS autoloader_demo.metadata.object (
  object_id         STRING    NOT NULL  COMMENT 'Unique id of the data object',
  object_type       STRING    NOT NULL  COMMENT 'source | target',

  -- ── SOURCE attributes ───────────────────────────────────────────────────────────────
  storage_account   STRING              COMMENT 'ADLS Gen2 storage account for abfss paths. NULL => file_path is used verbatim (e.g. a UC Volume path)',
  container         STRING              COMMENT 'ADLS container name (abfss only)',
  file_path         STRING              COMMENT 'Base path of source files. UC Volume: /Volumes/cat/schema/vol/...  |  abfss: path after the container',
  wildcard_pattern  STRING              COMMENT 'Glob appended to file_path, e.g. *.parquet or year=*/month=*/*.csv',
  file_format       STRING              COMMENT 'csv | json | jsonl | parquet | avro | xml',
  row_tag           STRING              COMMENT 'XML only — the row element tag (e.g. Order)',
  object_schema     STRING              COMMENT 'Optional explicit schema as a Spark JSON DDL string (headerless CSV / legacy files)',
  delimiter         STRING              COMMENT 'CSV only — field delimiter (default ,)',
  encoding          STRING              COMMENT 'CSV only — file encoding (default UTF-8)',
  null_value        STRING              COMMENT 'CSV only — token representing NULL',

  -- ── TARGET attributes ───────────────────────────────────────────────────────────────
  target_catalog    STRING              COMMENT 'Target Unity Catalog catalog',
  target_schema     STRING              COMMENT 'Target Unity Catalog schema',
  target_table      STRING              COMMENT 'Target table name',
  table_path        STRING              COMMENT 'Optional external Delta location (managed table if NULL)',
  partition_cols    STRING              COMMENT 'Comma-separated partition columns',
  merge_keys        STRING              COMMENT 'Comma-separated merge keys (used when load_type = merge)',

  description       STRING              COMMENT 'Human-readable description',
  created_at        TIMESTAMP           COMMENT 'Registration timestamp'
)
USING DELTA
COMMENT 'Registry of source and target data objects for the metadata-driven Auto Loader framework';


-- ─────────────────────────────────────────────────────────────────────────────────────
-- 2. operation — the unit of work. Binds one source object to one target object and
--    declares HOW the framework should ingest it. The runtime parameter is operation_id.
-- ─────────────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS autoloader_demo.metadata.operation (
  operation_id           STRING   NOT NULL  COMMENT 'Unique operation id — the single runtime parameter to the framework notebook',
  enabled                BOOLEAN  NOT NULL  COMMENT 'Only enabled operations are picked up by the scheduler/driver',
  source_object_id       STRING   NOT NULL  COMMENT 'FK -> object.object_id (object_type = source)',
  target_object_id       STRING   NOT NULL  COMMENT 'FK -> object.object_id (object_type = target)',

  load_type              STRING   NOT NULL  COMMENT 'append | merge | overwrite',
  merge_schema           BOOLEAN  NOT NULL  COMMENT 'Pass mergeSchema=true on append writes (absorb new columns)',
  schema_evolution_mode  STRING   NOT NULL  COMMENT 'Auto Loader cloudFiles.schemaEvolutionMode: addNewColumns | rescue | failOnNewColumns | none',
  cast_all_as_string     BOOLEAN  NOT NULL  COMMENT 'TRUE = faithful historical capture; land every column as STRING, type at Silver',
  multiline              BOOLEAN  NOT NULL  COMMENT 'JSON only — records span multiple lines',
  case_sensitive         BOOLEAN  NOT NULL  COMMENT 'Treat column names case-sensitively',
  max_files_per_trigger  INT                COMMENT 'Throttle files per micro-batch (NULL = Auto Loader default)',
  explode_key            STRING             COMMENT 'Top-level array key to explode for nested JSON (e.g. {"events":[...]})',

  description            STRING             COMMENT 'Human-readable description',
  created_at             TIMESTAMP          COMMENT 'Registration timestamp'
)
USING DELTA
COMMENT 'Operations binding sources to targets with declarative ingestion behavior';


-- ─────────────────────────────────────────────────────────────────────────────────────
-- 3. ingestion_audit_log — one row per framework run. The framework writes SUCCESS /
--    FAILED here in its finally-block so every run is observable regardless of outcome.
-- ─────────────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS autoloader_demo.metadata.ingestion_audit_log (
  operation_id   STRING     COMMENT 'Operation that ran',
  run_ts         TIMESTAMP  COMMENT 'Run completion timestamp',
  status         STRING     COMMENT 'SUCCESS | FAILED',
  duration_ms    BIGINT     COMMENT 'Wall-clock duration in milliseconds',
  rows_written   BIGINT     COMMENT 'Rows written across all micro-batches in this run',
  error_message  STRING     COMMENT 'Exception text when status = FAILED, else NULL'
)
USING DELTA
COMMENT 'Run-level audit log for every framework invocation';
